In [1]:
import pandas as pd

df = pd.read_excel('prep_test/check.xlsx')
df.head()

,일자,시간,HOT아메리카노 할인,ICE아메리카노 할인,NO WHIP,가은블랜딩원두100g,가은블랜딩원두200g,고구마라떼,골드메달 (애플),골드메달(스파클링),...,핫초코,햄.치즈샌드위치,행사) 아메리카노,행사) 아이스아메리카노,홍차라떼,화이트모카,화이트민트초코라떼,휘핑크림추가,히비스커스,합계
0,2022-03-02,8,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,20
1,2022-03-02,9,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,21
2,2022-03-02,10,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,21
3,2022-03-02,11,0,0,0,0,0,1,0,0,...,1,0,0,0,0,1,0,0,0,62
4,2022-03-02,12,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,47

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1911 entries, 0 to 1910
Columns: 118 entries, 일자 to 합계
dtypes: datetime64[ns](1), int64(117)
memory usage: 1.7 MB

In [5]:
new_df = df.iloc[:, 2:-1]
new_df.head()

,HOT아메리카노 할인,ICE아메리카노 할인,NO WHIP,가은블랜딩원두100g,가은블랜딩원두200g,고구마라떼,골드메달 (애플),골드메달(스파클링),녹차라떼,덜달게,...,할인,핫초코,햄.치즈샌드위치,행사) 아메리카노,행사) 아이스아메리카노,홍차라떼,화이트모카,화이트민트초코라떼,휘핑크림추가,히비스커스
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,1,0,...,0,1,0,0,0,0,1,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [5]:
new_df.to_excel("data/try.xlsx")

In [6]:
# 데이터 전처리: 각 행에서 주문량이 0 이상인 음료의 리스트를 만듦

preprocessed_data = []

for index, row in new_df.iterrows():
    order = []
    for beverage, quantity in row.items():
        if quantity > 0:
            order.extend([beverage] * quantity)  # 수량에 맞게 음료 이름 추가
    preprocessed_data.append(order)


# 리스트 앞 5개만 먼저 확인
preprocessed_data[:5]

[['바닐라라떼',
  '복숭아아이스티',
  '복숭아아이스티',
  '사이즈업 큰잔',
  '사이즈업 큰잔',
  '샷추가',
  '샷추가',
  '아메리카노',
  '아메리카노',
  '아이스바닐라라떼',
  '아이스아메리카노',
  '아이스아메리카노',
  '아이스아메리카노',
  '아이스아이리쉬라떼',
  '아이스연유라떼',
  '아이스토피넛라떼',
  '카페라떼',
  '카페라떼',
  '카페라떼',
  '텀블러, 머그할인'],
 ['딸기연유라떼 14oz',
  '복숭아아이스티',
  '복숭아아이스티',
  '사이즈업 중간잔 (AME)',
  '사이즈업 큰잔',
  '사이즈업 큰잔',
  '샷추가',
  '샷추가',
  '시럽추가',
  '아메리카노',
  '아메리카노',
  '아메리카노',
  '아이스바닐라라떼',
  '아이스아메리카노',
  '아이스카라멜마끼아또',
  '아이스카페라떼',
  '아이스카페라떼',
  '카페라떼',
  '카페라떼',
  '텀블러, 머그할인',
  '햄.치즈샌드위치'],
 ['복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '사이즈업 중간잔 (AME)',
  '샷추가',
  '석류아이스티',
  '석류아이스티',
  '아메리카노',
  '아메리카노',
  '아이스민트초코(휘핑)',
  '아이스아메리카노',
  '아이스아메리카노',
  '아이스아메리카노',
  '아이스초코(휘핑)',
  '유자차',
  '청포도에이드',
  '카푸치노',
  '카푸치노',
  '쿠키',
  '텀블러, 머그할인',
  '햄.치즈샌드위치'],
 ['고구마라떼',
  '녹차라떼',
  '딸기연유라떼 14oz',
  '딸기연유라떼 14oz',
  '레몬에이드',
  '바닐라라떼',
  '바닐라라떼',
  '바닐라라떼',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '사이즈업 중간잔 (AME)',
  '사이즈업 중간잔 (AME)',
  '사이즈업 중간잔 (AME)',
  '사이즈업 중간잔 (AME)',
  '사이즈업 큰잔',
  '사이즈업 큰잔',
  '사이즈업 큰잔',
  '사이즈업 큰잔',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '석류아이스티',
  '석류아이스티',
  '아이스녹차라떼',
  '아이스바닐라라떼',
  '아이스바닐라라떼',
  '아이스아메리카노',
  '아이스아메리카노',
  '아이스아메리카노',
  '아이스아메리카노',
  '아이스카페라떼',
  '아이스홍차라떼',
  '연유라떼',
  '유자차',
  '자몽에이드',
  '젤라또',
  '젤라또',
  '카페라떼',
  '쿠키',
  '쿠키',
  '텀블러, 머그할인',
  '텀블러, 머그할인',
  '핫초코',
  '화이트모카'],
 ['복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '사이즈업 중간잔 (AME)',
  '사이즈업 큰잔',
  '사이즈업 큰잔',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '석류아이스티',
  '아메리카노',
  '아메리카노',
  '아메리카노',
  '아메리카노',
  '아메리카노',
  '아이스딸기라떼',
  '아이스바닐라라떼',
  '아이스바닐라라떼',
  '아이스아메리카노',
  '아이스아메리카노',
  '아이스아메리카노',
  '아이스아메리카노',
  '아이스아메리카노',
  '아이스아메리카노',
  '아이스연유라떼',
  '아이스카페라떼',
  '아이스카페라떼',
  '아이스카페라떼',
  '아이스카페라떼',
  '천혜향차',
  '카야샌드위치',
  '카페라떼',
  '카페라떼',
  '캐리어',
  '쿠폰',
  '텀블러, 머그할인',
  '홍차라떼']]

In [7]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth

# 트랜잭션 인코딩
te = TransactionEncoder()
te_ary = te.fit(preprocessed_data).transform(preprocessed_data)
df = pd.DataFrame(te_ary, columns=te.columns_)

df

,HOT아메리카노 할인,ICE아메리카노 할인,NO WHIP,가은블랜딩원두100g,가은블랜딩원두200g,고구마라떼,골드메달 (애플),골드메달(스파클링),녹차라떼,덜달게,...,할인,핫초코,햄.치즈샌드위치,행사) 아메리카노,행사) 아이스아메리카노,홍차라떼,화이트모카,화이트민트초코라떼,휘핑크림추가,히비스커스
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,False,True,False,...,False,True,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1906,False,False,False,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1907,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,True,False,False,False
1908,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1909,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1910,False,False,False,False,False,False,True,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [8]:
# FP-Growth algorithm 적용
# support 임계치 설정, 애초에 FP-Growth는 Frequent Pattern이기 때문에 빈도수 보는거라 support 값만 처리
min_support = 0.35
frequent_itemsets = fpgrowth(df, min_support=min_support, use_colnames=True)

frequent_itemsets.head()

    support     itemsets
0  0.929356    (복숭아아이스티)
1  0.902145        (샷추가)
2  0.888017   (아이스아메리카노)
3  0.788069    (사이즈업 큰잔)
4  0.695971  (텀블러, 머그할인)

In [9]:
frequent_itemsets = frequent_itemsets.sort_values(by=['support'], ascending=False)   # support값 내림차순 정렬
frequent_itemsets.head()

     support             itemsets
0   0.929356            (복숭아아이스티)
1   0.902145                (샷추가)
19  0.889587       (복숭아아이스티, 샷추가)
2   0.888017           (아이스아메리카노)
20  0.842491  (아이스아메리카노, 복숭아아이스티)

In [10]:
frequent_itemsets.to_excel("fpgrowth_new_result_min35.xlsx", index=False)    # fpgrowth 상태 엑셀파일 추출

In [11]:
from mlxtend.frequent_patterns import association_rules

# 연관 규칙 생성
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.4)     # 신뢰도 임계값 설정

# 신뢰도와 향상도 포함하여 규칙 확인
rules[["antecedents", "consequents", "support", "confidence", "lift"]]

,antecedents,consequents,support,confidence,lift
0,(복숭아아이스티),(샷추가),0.889587,0.957207,1.061034
1,(샷추가),(복숭아아이스티),0.889587,0.986079,1.061034
2,(아이스아메리카노),(복숭아아이스티),0.842491,0.948733,1.020850
3,(복숭아아이스티),(아이스아메리카노),0.842491,0.906532,1.020850
4,(아이스아메리카노),(샷추가),0.824176,0.928108,1.028779
...,...,...,...,...,...
5253,"(아메리카노, 아이스아메리카노)",(사이즈업 중간잔 (AME)),0.350078,0.697602,1.104488
5254,"(아메리카노, 사이즈업 중간잔 (AME))",(아이스아메리카노),0.350078,0.983824,1.107888
5255,"(아이스아메리카노, 사이즈업 중간잔 (AME))",(아메리카노),0.350078,0.584790,1.117534
5256,(아메리카노),"(아이스아메리카노, 사이즈업 중간잔 (AME))",0.350078,0.669000,1.117534
5257,(사이즈업 중간잔 (AME)),"(아메리카노, 아이스아메리카노)",0.350078,0.554267,1.104488

In [27]:
type(rules)

pandas.core.frame.DataFrame

In [12]:
rules.to_excel("association_new_rule_min35n40.xlsx", index=False)