In [1]:
import pandas as pd

df = pd.read_csv('merge_menu_sum.csv')
df.head()

,고구마라떼,녹차라떼,딸기라떼,딸기스무디,딸기연유라떼 14oz,레모니카노,레몬글라스,레몬에이드,레몬차,레몬차 ICE,...,페퍼민트,플레인스무디,핫초코,햄.치즈샌드위치,홍차라떼,화이트모카,화이트민트초코라떼,히비스커스,아이스아메리카노,아메리카노
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,3,2
1,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,3
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,3,2
3,1,1,0,0,2,0,0,1,0,0,...,0,0,1,0,0,1,0,0,4,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,6,5

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1911 entries, 0 to 1910
Data columns (total 88 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   고구마라떼           1911 non-null   int64
 1   녹차라떼            1911 non-null   int64
 2   딸기라떼            1911 non-null   int64
 3   딸기스무디           1911 non-null   int64
 4   딸기연유라떼 14oz     1911 non-null   int64
 5   레모니카노           1911 non-null   int64
 6   레몬글라스           1911 non-null   int64
 7   레몬에이드           1911 non-null   int64
 8   레몬차             1911 non-null   int64
 9   레몬차 ICE         1911 non-null   int64
 10  망고스무디           1911 non-null   int64
 11  망고에이드           1911 non-null   int64
 12  민트초코            1911 non-null   int64
 13  바닐라라떼           1911 non-null   int64
 14  복숭아아이스티         1911 non-null   int64
 15  블루베리라떼          1911 non-null   int64
 16  블루베리스무디         1911 non-null   int64
 17  생강차             1911 non-null   int64
 18  생강차 ICE         1911 non-null   int64
 19  샷추가             1911 non-null   int64
 20  석류아이스티          1911 non-null   int64
 21  아이리쉬라떼          1911 non-null   int64
 22  아이스 레몬글라스       1911 non-null   int64
 23  아이스 얼그레이홍차      1911 non-null   int64
 24  아이스 잉글리쉬 블랙퍼스트  1911 non-null   int64
 25  아이스 캐모마일        1911 non-null   int64
 26  아이스 페퍼민트        1911 non-null   int64
 27  아이스 히비스커스       1911 non-null   int64
 28  아이스고구마라떼        1911 non-null   int64
 29  아이스녹차라떼         1911 non-null   int64
 30  아이스딸기라떼         1911 non-null   int64
 31  아이스레모니카노        1911 non-null   int64
 32  아이스민트초코(휘핑)     1911 non-null   int64
 33  아이스바닐라라떼        1911 non-null   int64
 34  아이스블루베리라떼       1911 non-null   int64
 35  아이스아이리쉬라떼       1911 non-null   int64
 36  아이스연유라떼         1911 non-null   int64
 37  아이스오곡라떼         1911 non-null   int64
 38  아이스초코(휘핑)       1911 non-null   int64
 39  아이스카라멜마끼아또      1911 non-null   int64
 40  아이스카페라떼         1911 non-null   int64
 41  아이스카페모카         1911 non-null   int64
 42  아이스토피넛라떼        1911 non-null   int64
 43  아이스토피넛모카        1911 non-null   int64
 44  아이스홍차라떼         1911 non-null   int64
 45  아이스화이트모카        1911 non-null   int64
 46  아이스화이트민트초코라떼    1911 non-null   int64
 47  아포가토            1911 non-null   int64
 48  얼그레이홍차          1911 non-null   int64
 49  에스프레소           1911 non-null   int64
 50  연유라떼            1911 non-null   int64
 51  오곡라떼            1911 non-null   int64
 52  오렌지에이드          1911 non-null   int64
 53  우유              1911 non-null   int64
 54  유자스무디           1911 non-null   int64
 55  유자에이드           1911 non-null   int64
 56  유자차             1911 non-null   int64
 57  유자차 ICE         1911 non-null   int64
 58  잉글리쉬 블랙퍼스트      1911 non-null   int64
 59  자몽에이드           1911 non-null   int64
 60  자몽차             1911 non-null   int64
 61  자몽차 ICE         1911 non-null   int64
 62  젤라또             1911 non-null   int64
 63  천혜향스무디          1911 non-null   int64
 64  천혜향에이드          1911 non-null   int64
 65  천혜향차            1911 non-null   int64
 66  천혜향차 ICE        1911 non-null   int64
 67  청포도에이드          1911 non-null   int64
 68  카라멜마끼아또         1911 non-null   int64
 69  카야샌드위치          1911 non-null   int64
 70  카페라떼            1911 non-null   int64
 71  카페모카            1911 non-null   int64
 72  카푸치노            1911 non-null   int64
 73  캐모마일            1911 non-null   int64
 74  커피원두1.0kg       1911 non-null   int64
 75  크림치즈샌드위치        1911 non-null   int64
 76  토피넛라떼           1911 non-null   int64
 77  토피넛모카           1911 non-null   int64
 78  페퍼민트            1911 non-null   int64
 79  플레인스무디          1911 non-null   int64
 80  핫초코             1911 non-null   int64
 81  햄.치즈샌드위치        1911 non-null   int64
 82  홍차라떼            1911 non-null   int64
 83  화이트모카           1911 non-null   int64
 84  화이트민트초코라떼       1911 non-null   int64
 85  히비스커스           1911 non-null   int64
 86  아이스아메리카노        1911 non-null   int64
 87  아메리카노           1911 non-null   int64
dtypes: int64(88)
memory usage: 1.3 MB

In [3]:
# 데이터 전처리: 각 행에서 주문량이 0 이상인 음료의 리스트를 만듦

preprocessed_data = []

for index, row in df.iterrows():
    order = []
    for beverage, quantity in row.items():
        if quantity > 0:
            order.extend([beverage] * quantity)  # 수량에 맞게 음료 이름 추가
    preprocessed_data.append(order)


# 리스트 앞 5개만 먼저 확인
preprocessed_data[:5]

[['바닐라라떼',
  '복숭아아이스티',
  '복숭아아이스티',
  '샷추가',
  '샷추가',
  '아이스바닐라라떼',
  '아이스아이리쉬라떼',
  '아이스연유라떼',
  '아이스토피넛라떼',
  '카페라떼',
  '카페라떼',
  '카페라떼',
  '아이스아메리카노',
  '아이스아메리카노',
  '아이스아메리카노',
  '아메리카노',
  '아메리카노'],
 ['딸기연유라떼 14oz',
  '복숭아아이스티',
  '복숭아아이스티',
  '샷추가',
  '샷추가',
  '아이스바닐라라떼',
  '아이스카라멜마끼아또',
  '아이스카페라떼',
  '아이스카페라떼',
  '카페라떼',
  '카페라떼',
  '햄.치즈샌드위치',
  '아이스아메리카노',
  '아메리카노',
  '아메리카노',
  '아메리카노'],
 ['복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '샷추가',
  '석류아이스티',
  '석류아이스티',
  '아이스민트초코(휘핑)',
  '아이스초코(휘핑)',
  '유자차',
  '청포도에이드',
  '카푸치노',
  '카푸치노',
  '햄.치즈샌드위치',
  '아이스아메리카노',
  '아이스아메리카노',
  '아이스아메리카노',
  '아메리카노',
  '아메리카노'],
 ['고구마라떼',
  '녹차라떼',
  '딸기연유라떼 14oz',
  '딸기연유라떼 14oz',
  '레몬에이드',
  '바닐라라떼',
  '바닐라라떼',
  '바닐라라떼',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '석류아이스티',
  '석류아이스티',
  '아이스녹차라떼',
  '아이스바닐라라떼',
  '아이스바닐라라떼',
  '아이스카페라떼',
  '아이스홍차라떼',
  '연유라떼',
  '유자차',
  '자몽에이드',
  '젤라또',
  '젤라또',
  '카페라떼',
  '핫초코',
  '화이트모카',
  '아이스아메리카노',
  '아이스아메리카노',
  '아이스아메리카노',
  '아이스아메리카노'],
 ['복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '복숭아아이스티',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '샷추가',
  '석류아이스티',
  '아이스딸기라떼',
  '아이스바닐라라떼',
  '아이스바닐라라떼',
  '아이스연유라떼',
  '아이스카페라떼',
  '아이스카페라떼',
  '아이스카페라떼',
  '아이스카페라떼',
  '천혜향차',
  '카야샌드위치',
  '카페라떼',
  '카페라떼',
  '홍차라떼',
  '아이스아메리카노',
  '아이스아메리카노',
  '아이스아메리카노',
  '아이스아메리카노',
  '아이스아메리카노',
  '아이스아메리카노',
  '아메리카노',
  '아메리카노',
  '아메리카노',
  '아메리카노',
  '아메리카노']]

In [4]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth

# 트랜잭션 인코딩
te = TransactionEncoder()
te_ary = te.fit(preprocessed_data).transform(preprocessed_data)
df = pd.DataFrame(te_ary, columns=te.columns_)

df

,고구마라떼,녹차라떼,딸기라떼,딸기스무디,딸기연유라떼 14oz,레모니카노,레몬글라스,레몬에이드,레몬차,레몬차 ICE,...,토피넛라떼,토피넛모카,페퍼민트,플레인스무디,핫초코,햄.치즈샌드위치,홍차라떼,화이트모카,화이트민트초코라떼,히비스커스
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
3,True,True,False,False,True,False,False,True,False,False,...,False,False,False,False,True,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1906,False,False,False,False,True,False,False,False,True,False,...,False,False,True,False,True,False,False,False,False,False
1907,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1908,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
1909,True,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1910,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [5]:
# FP-Growth algorithm 적용
# support 임계치 설정, 애초에 FP-Growth는 Frequent Pattern이기 때문에 빈도수 보는거라 support 값만 처리
min_support = 0.35
frequent_itemsets = fpgrowth(df, min_support=min_support, use_colnames=True)

frequent_itemsets.head()

    support    itemsets
0  0.929356   (복숭아아이스티)
1  0.926740  (아이스아메리카노)
2  0.902145       (샷추가)
3  0.605965  (아이스바닐라라떼)
4  0.555730     (아메리카노)

In [6]:
frequent_itemsets = frequent_itemsets.sort_values(by=['support'], ascending=False)   # support값 내림차순 정렬
frequent_itemsets.head()

     support             itemsets
0   0.929356            (복숭아아이스티)
1   0.926740           (아이스아메리카노)
2   0.902145                (샷추가)
14  0.889587       (복숭아아이스티, 샷추가)
13  0.880167  (복숭아아이스티, 아이스아메리카노)

In [7]:
from mlxtend.frequent_patterns import association_rules

# 연관 규칙 생성
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)     # 신뢰도 임계값 설정

# 신뢰도와 향상도 포함하여 규칙 확인
rules[["antecedents", "consequents", "support", "confidence", "lift"]].sort_values(by='confidence', ascending=False)   # confidence 기준으로 내림차순

,antecedents,consequents,support,confidence,lift
392,"(샷추가, 젤라또)",(복숭아아이스티),0.380952,0.998628,1.074538
542,"(샷추가, 아이스아메리카노, 젤라또)",(복숭아아이스티),0.365254,0.998569,1.074474
517,"(샷추가, 석류아이스티, 아이스카페라떼)",(복숭아아이스티),0.366824,0.997155,1.072952
527,"(샷추가, 아이스아메리카노, 아이스홍차라떼)",(복숭아아이스티),0.366300,0.997151,1.072948
599,"(샷추가, 석류아이스티, 아이스아메리카노, 아이스카페라떼)",(복숭아아이스티),0.363684,0.997131,1.072926
...,...,...,...,...,...
652,(아이스카페라떼),"(복숭아아이스티, 샷추가, 햄.치즈샌드위치)",0.361591,0.502545,1.079061
257,(샷추가),"(복숭아아이스티, 햄.치즈샌드위치, 아이스아메리카노)",0.453166,0.502320,1.084671
293,"(복숭아아이스티, 아이스아메리카노)","(샷추가, 카페라떼)",0.441130,0.501189,1.095849
151,(복숭아아이스티),"(샷추가, 햄.치즈샌드위치)",0.465725,0.501126,1.068808
663,(아이스카페라떼),"(샷추가, 햄.치즈샌드위치, 아이스아메리카노)",0.360544,0.501091,1.099408

In [8]:
type(rules)

pandas.core.frame.DataFrame

In [9]:
rules.to_excel("association_new_rule_min35n40.xlsx", index=False)